apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: event-platform
  labels:
    app: payments
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: payments

  template:
    metadata:
      labels:
        app: payments
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"

    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30

      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: payments
          image: ghcr.io/abhizenin/event-driven-microservices-payments:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8002

          envFrom:
            - configMapRef:
                name: platform-config

          env:
            - name: SERVICE
              value: payments
            - name: PORT
              value: "8002"

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: event-platform
spec:
  selector:
    app: payments
  ports:
    - name: http
      port: 8002
      targetPort: http
